server:
  port: 8081

spring:
  application:
    name: payment-gateway-service
  kafka:
    bootstrap-servers: localhost:9092
  web:
    resources:
      static-locations: classpath:/static/

nats:
  server:
    url: nats://localhost:4222
  timeout:
    ms: 2000

logging:
  level:
    root: INFO
    com.fintech.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
